import { useState } from 'react'
import { Bell, BookOpen, Box, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Command, Component, FileText, LayoutDashboard, Menu, Monitor, Moon, PanelLeftClose, Plus, Search, Settings2, Sparkles, Sun, Tablet, X } from 'lucide-react'
import { currentRelease } from './data/releases'
import './App.css'

type PreviewSize = 'desktop' | 'tablet' | 'mobile'

const navGroups = [
  { label: 'SYSTEM', items: [{ icon: LayoutDashboard, label: 'Overview', active: true }, { icon: Box, label: 'Foundations', caret: true }, { icon: Component, label: 'Components', badge: '12', caret: true }, { icon: BookOpen, label: 'Patterns', badge: '4', caret: true }, { icon: FileText, label: 'Templates', badge: '1', caret: true }] },
  { label: 'WORKSPACE', items: [{ icon: Clock3, label: 'Changelog', badge: '3' }, { icon: Settings2, label: 'Settings' }] },
]
function App() {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const [darkMode, setDarkMode] = useState(false)
  const [previewSize, setPreviewSize] = useState<PreviewSize>('desktop')
  return <main className={darkMode ? 'app dark' : 'app'}>
    <aside className={sidebarOpen ? 'sidebar open' : 'sidebar'}>
      <div className="brand-row"><div className="brand-mark"><Command size={17} strokeWidth={2.4} /></div><div className="brand-title">Service Dashboard</div><button className="icon-button mobile-close" onClick={() => setSidebarOpen(false)} aria-label="메뉴 닫기"><X size={18} /></button></div>
      <div className="workspace-switcher"><div className="workspace-logo">AD</div><div><strong>Admin Design System</strong><span>Personal workspace</span></div><ChevronDown size={15} /></div>
      <nav className="navigation" aria-label="서비스 대시보드 메뉴">{navGroups.map(group => <section key={group.label} className="nav-group"><p className="nav-label">{group.label}</p>{group.items.map(item => { const Icon = item.icon; const isActive = 'active' in item && item.active; const hasCaret = 'caret' in item && item.caret; return <button key={item.label} className={isActive ? 'nav-item active' : 'nav-item'}><Icon size={16} strokeWidth={isActive ? 2.2 : 1.8} /><span>{item.label}</span>{item.badge && <em>{item.badge}</em>}{hasCaret && <ChevronRight className="caret" size={14} />}</button> })}</section>)}</nav>
      <div className="sidebar-bottom"><div className="version-card"><span className="version-dot" /><div><strong>{currentRelease.version}</strong><span>첫 번째 기준선</span></div><ChevronRight size={15} /></div><button className="help-row"><CircleHelp size={16} /> 시스템 사용 원칙</button></div>
    </aside>
    {sidebarOpen && <button className="sidebar-overlay" onClick={() => setSidebarOpen(false)} aria-label="메뉴 닫기" />}
    <section className="main-panel">
      <header className="topbar"><button className="icon-button mobile-menu" onClick={() => setSidebarOpen(true)} aria-label="메뉴 열기"><Menu size={20} /></button><div className="crumbs"><span>Admin Design System</span><ChevronRight size={14} /><strong>Overview</strong></div><div className="top-actions"><button className="search-button"><Search size={16} /><span>빠른 검색</span><kbd>⌘ K</kbd></button><button className="icon-button theme-button" onClick={() => setDarkMode(!darkMode)} aria-label="테마 변경">{darkMode ? <Sun size={17} /> : <Moon size={17} />}</button><div className="notification-wrap"><button className="icon-button notification-button" onClick={() => setNotificationsOpen(!notificationsOpen)} aria-label="업데이트 알림"><Bell size={17} /><i /></button>{notificationsOpen && <div className="notification-popover"><div className="popover-heading"><strong>업데이트 알림</strong><button>모두 읽음</button></div><div className="notification-entry"><span className="update-icon"><Sparkles size={14} /></span><div><strong>{currentRelease.version}이 준비됐어요</strong><p>이번 버전의 변경 {currentRelease.changes.length}개를 확인하세요.</p><small>{currentRelease.publishedAt}</small></div></div><button className="popover-footer">Changelog 열기 <ChevronRight size={14} /></button></div>}</div><button className="avatar" aria-label="내 프로필">Y</button></div></header>
      <div className="content">
        <section className="page-intro"><div><div className="eyebrow"><span /> SERVICE DASHBOARD</div><h1>디자인 시스템 현황</h1><p>어드민 경험을 위한 기준을 만들고, 변화가 잘 반영됐는지 확인하세요.</p></div><button className="primary-button"><Plus size={16} /> 새 검증 항목</button></section>
        <section className="release-banner"><div className="release-icon"><Sparkles size={18} /></div><div className="release-copy"><span className="release-pill">NEW RELEASE</span><strong>{currentRelease.version} · {currentRelease.title}</strong><p>{currentRelease.description}</p></div><button className="secondary-button">업데이트 보기 <ChevronRight size={15} /></button></section>
        <section className="stats-grid" aria-label="디자인 시스템 요약"><StatCard label="Foundations" value="05" note="Color · Type · Spacing" icon={<Box size={18} />} accent="purple" /><StatCard label="Components" value="12" note="8개 검증 완료" icon={<Component size={18} />} accent="blue" /><StatCard label="Patterns" value="04" note="목록·입력·피드백" icon={<PanelLeftClose size={18} />} accent="orange" /><StatCard label="Review queue" value={String(currentRelease.reviewItems.length).padStart(2, '0')} note="다음 업데이트 검토" icon={<Clock3 size={18} />} accent="green" /></section>
        <section className="dashboard-grid"><article className="panel anatomy-panel"><div className="panel-head"><div><span className="section-overline">COMPONENT INSPECTION</span><h2>Button anatomy</h2></div><button className="text-button">컴포넌트 보기 <ChevronRight size={14} /></button></div><p className="panel-description">모든 variation은 같은 구조와 명확한 역할을 공유합니다.</p><div className="anatomy-stage"><div className="anatomy-label label-container"><b>Container</b><span>높이 36 · radius 6</span></div><div className="anatomy-label label-icon"><b>Leading icon</b><span>16 × 16</span></div><div className="anatomy-label label-label"><b>Label</b><span>Medium · 14</span></div><button className="anatomy-button"><Plus size={16} /> 새 사용자</button><span className="anatomy-line line-container" /><span className="anatomy-line line-icon" /><span className="anatomy-line line-label" /></div><div className="status-row"><span><i className="status-dot stable" /> Stable</span><span>Button / Primary / Default</span><span className="last-changed">{currentRelease.version}에서 검증됨</span></div></article><article className="panel updates-panel"><div className="panel-head"><div><span className="section-overline">CHANGELOG</span><h2>최근 변경</h2></div><button className="text-button">전체 보기 <ChevronRight size={14} /></button></div><div className="change-list">{currentRelease.changes.map(item => <div className="change-item" key={item.name}><div className={`change-symbol ${item.type === 'New' ? 'new' : ''}`}>{item.icon}</div><div><strong>{item.name}</strong><p>{item.note}</p></div><span className={item.type === 'New' ? 'tiny-badge new' : 'tiny-badge'}>{item.type}</span></div>)}</div></article></section>
        <section className="panel responsive-panel"><div className="panel-head responsive-head"><div><span className="section-overline">RESPONSIVE CHECK</span><h2>목록 패턴 미리보기</h2><p className="panel-description">화면 너비에 따라 정보 밀도와 액션의 우선순위가 달라집니다.</p></div><div className="device-switcher"><DeviceButton active={previewSize === 'desktop'} onClick={() => setPreviewSize('desktop')} icon={<Monitor size={15} />} label="Desktop" /><DeviceButton active={previewSize === 'tablet'} onClick={() => setPreviewSize('tablet')} icon={<Tablet size={15} />} label="Tablet" /><DeviceButton active={previewSize === 'mobile'} onClick={() => setPreviewSize('mobile')} icon={<Menu size={15} />} label="Mobile" /></div></div><div className={`preview-shell ${previewSize}`}><div className="preview-top"><div><b>사용자 관리</b><span>전체 사용자와 상태를 관리합니다.</span></div><button><Plus size={13} /> 사용자 추가</button></div><div className="preview-filter"><div><Search size={13} /><span>이름 또는 이메일 검색</span></div><button>상태 <ChevronDown size={12} /></button><button className="filter-more">가입일 <ChevronDown size={12} /></button></div><div className="preview-table"><div className="table-head"><span>사용자</span><span>상태</span><span>마지막 활동</span><span /></div><Row initials="MH" name="민지 한" email="minji@company.co" status="활성" date="방금 전" /><Row initials="SJ" name="서준 김" email="seojun@company.co" status="초대됨" date="2일 전" warm /></div></div><div className="preview-meta"><span><i className="status-dot stable" /> {previewSize === 'desktop' ? '1440 px · 전체 컬럼 표시' : previewSize === 'tablet' ? '768 px · 보조 필터 축소' : '375 px · 핵심 정보 우선'}</span><button>이 case 기록하기 <ChevronRight size={14} /></button></div></section>
        <section className="bottom-grid"><article className="panel principle-panel"><div className="panel-head"><div><span className="section-overline">SYSTEM PRINCIPLE</span><h2>이번 주의 원칙</h2></div><button className="square-button"><ChevronRight size={16} /></button></div><blockquote>“정보 밀도는 높게, 의사결정의 부담은 낮게.”</blockquote><p>어드민은 더 많은 데이터를 보여주되, 중요한 다음 행동이 흐려지지 않도록 설계합니다.</p><div className="principle-tags"><span>Data density</span><span>Clear hierarchy</span><span>Safe actions</span></div></article><article className="panel checklist-panel"><div className="panel-head"><div><span className="section-overline">REVIEW QUEUE</span><h2>다음 검증 항목</h2></div><span className="count-pill">{currentRelease.reviewItems.length}</span></div><ul>{currentRelease.reviewItems.map(item => <li key={item.label}><span><i className={item.completed ? 'check-circle' : 'check-circle empty'}>{item.completed && <Check size={11} />}</i> {item.label}</span><em>{item.category}</em></li>)}</ul></article></section>
      </div>
    </section>
  </main>
}
function Row({ initials, name, email, status, date, warm }: { initials: string, name: string, email: string, status: string, date: string, warm?: boolean }) { return <div className="table-row"><div className="user-cell"><i className={warm ? 'warm' : ''}>{initials}</i><span><b>{name}</b><small>{email}</small></span></div><span className={status === '활성' ? 'active-badge' : 'active-badge muted'}>{status}</span><span className="date-cell">{date}</span><button className="dots">•••</button></div> }
function StatCard({ label, value, note, icon, accent }: { label: string, value: string, note: string, icon: React.ReactNode, accent: string }) { return <article className={`stat-card ${accent}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><p>{note}</p></div></article> }
function DeviceButton({ active, onClick, icon, label }: { active: boolean, onClick: () => void, icon: React.ReactNode, label: string }) { return <button onClick={onClick} className={active ? 'device-button selected' : 'device-button'}>{icon}<span>{label}</span></button> }
export default App
